SELECT * FROM employee;
SELECT * FROM department;
SELECT * FROM job;
SELECT * FROM LOCATION;
SELECT * FROM SAL_GRADE;
SELECT * FROM
(SELECT E.*, D.DEPT_TITLE, DECODE(SUBSTR(emp_no,8,1),'1','M','3','M','2','F','4','F') AS GENDER FROM EMPLOYEE E  JOIN DEPARTMENT D ON (dept_code=dept_id)) 
WHERE salary >= 1000000 ;
SELECT * FROM employee WHERE hire_date < sysdate;
SELECT * FROM employee JOIN DEPARTMENt on(dept_code=dept_id) JOIN job USING(job_code) JOIN LOCATION ON(LOCAL_CODE=LOCATION_ID);
SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, DEPT_TITLE, JOB_NAME, SAL_LEVEL, SALARY,BONUS, MANAGER_ID, HIRE_DATE, ENT_DATE, ENT_YN, NATIONAL_CODE FROM employee JOIN DEPARTMENt on(dept_code=dept_id) JOIN job USING(job_code) JOIN LOCATION ON(LOCAL_CODE=LOCATION_ID) ;